name: openalbion_weaponry
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

   #model control
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  freezed: ^2.3.2

  #networking
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.6
  dartz: ^0.10.1

  #state management
  provider: ^6.0.5

  #ui
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  shimmer: ^2.0.0
  dropdown_button2: ^2.1.2

  #helper
  change_app_package_name: ^1.1.0
  package_info_plus: ^4.0.0
  flutter_dotenv: ^5.0.2

  #local notification
  flutter_local_notifications: ^14.0.0+2

  #localization
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.12.0
  firebase_analytics: ^10.4.0
  firebase_messaging: ^14.6.0

  #persistence
  shared_preferences: ^2.1.1
  firebase_app_check: ^0.1.4+1

dev_dependencies:
  build_runner:
  retrofit_generator: ^6.0.0+3
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/svgs/
    - assets/images/pngs/
    - assets/fonts/inter/
    - assets/mock_json/
    - .env


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/inter.ttf
